"use client";
import { useEffect } from "react";

import "./globals.css";

import Header from "@/components/Header";


import Footer from "@/components/Footer";



//export const metadata = {
//title: "Create Next App",
//description: "Generated by create next app",
//};

export default function RootLayout({ children }) {

  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  return (
    <html lang="en">
      <body >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
